/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 24.11.2011, 15:50:10
 */

package Presenter.Graphics.Space.G2D;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author kalinin
 */
public class NewJFrame extends javax.swing.JFrame {
    BufferedImage im1;
    BufferedImage im2;
    Graphics2D g1;
    Graphics2D g2;
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        im1=new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        im2=new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        g1=(Graphics2D) im1.getGraphics();
        g2=(Graphics2D) im2.getGraphics();

        g1.drawRect(0, 0, 100, 100);
        g2.drawRect(1, 1, 99, 98);
        g1.setBackground(Color.white);
        g2.setBackground(Color.white);
        g1.setColor(Color.red);
        g2.setColor(Color.green);

        g1.fillRect(10, 10, 50, 50);
        g2.fillRect(30, 30, 50, 50);


      //  g1.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
        g1.drawImage(im2, 0, 0, null);

        
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(im1,20, 20, null);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
